export enum SequenceState {
  IDLE = 'IDLE',
  SCENE_1_BALANCE = 'SCENE_1_BALANCE',
  SCENE_2_TUNNEL = 'SCENE_2_TUNNEL',
  SCENE_3_REVEAL = 'SCENE_3_REVEAL',
  SCENE_4_LOGO = 'SCENE_4_LOGO',
  SCENE_5_ENTRY = 'SCENE_5_ENTRY',
  SCENE_6_OUTRO = 'SCENE_6_OUTRO',
  FINISHED = 'FINISHED'
}